[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_token = "5iXkkKneqKpEBrdaTbD7MKBr6WhoJqeoR55ohCLp3qTc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/pidorasik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
